class Considerations {
  static Map<ConsiderationType, List<String>> considerationsYoutubeUrls = {
    ConsiderationType.LANGUSTA_2018: ["QcjjXVxPc0c",
      "QPurZTKIWcM",
      "c8WHRHNxJDA",
      "SwXuUfbKknM",
      "Jdd5s2oAX7g",
      "AGIUpMa45LY",
      "dn_lt5Vi_1I",
      "2yWyRPqMcxA",
      "9QuFnuRIDzA",
      "aA6i_BnzkLc",
      "je8PxtO5U4U",
      "IlQLeE_LV5M",
      "SCSSqR-8Nuo",
      "CKgXUny5j5c",
      "lzJEqx_MC9s",
      "a5MdSQqT38U",
      "_MXZQaGoWd8",
      "iSLTd3_Kww0",
      "DAwCl0Ormd0",
      "qItWhXfjN4s",
      "O2n7DxRsGyQ",
      "D02JanUSYQ8",
      "jZv8IYTiKiI",
      "lufO4-g8zSg",
      "BP-5XxQnqnQ",
      "XQrONBYSm4w",
      "WAzleuWO8SY",
      "X7on0qHBrZ8",
      "LQ6uYHWdSlI",
      "4W4hMhF21u0",
      "fgaacNCe8mc",
      "_Hb4ik7CEJA",
      "c5JuNOyqpJ0",
      "kh-TMx9nYEc",
      "vZ6mdYsuF50",
      "6BlFRmObPTQ",
      "CgwzOQmr1kc",
      "XPnztkaFpag",
      "k8UITbaeHCI",
      "jjvITCcS1m8",
      "pPqfvywXiiw",
      "3kdIHJq-DEw",
      "L1aFg23RR7E",
      "M4ISmMgnYOw",
      "9Y2zE1VBX54",
      "fP7ltITUGbk",
      "j569cHxgXXE",
      "6ZhzmVZoPZ8",
      "Oui1lSxDF4g",
      "Nmv8nHohxqU",
      "OgsJOFQloog",
      "dTlRcDIpPzA",
      "ENkdnY6cZsc",
      "dXSZM1hqRmo"]
  };
  static String getConsiderationYoutubeUrlForDay(ConsiderationType considerationType, int novenaDay){
    return considerationsYoutubeUrls[considerationType][novenaDay];
  }
}

enum ConsiderationKind { TEXT, YOUTUBE }
enum ConsiderationType { LANGUSTA_2016, LANGUSTA_2017, LANGUSTA_2018 }
